name: Update README

on:
  schedule:
    - cron: '0 * * * *' # 매 시간마다 자동으로 업데이트
  workflow_dispatch: # 필요할 때 수동으로도 실행 가능

permissions:
  contents: write # 권한
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/user-activity-workflow@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "Update recent activity"
          MAX_LINES: 5 # 보여줄 활동 개수
